# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 462017157983695ee976b4fd10c9f62a864c8bfd66b7ef9c00212313921313ac8894305ec239669052562e8665c251f6b2acfd21e0351e8b975ccb14eebbdcc7

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 6f33a5d4a84079f3f653b4a65d5c92a72bc2a5d5a0ee9e215b126baedf6bb33e08bae2e8ed80e2d09a97b6bcd646f539c28eef72a986e94d3806801b7490b6cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
